name: Build

on: 
  push:
    branches:   
      - master
    tags:
      - 'test[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

jobs:

  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install EB CLI
        run: |
          git  log --pretty=oneline
